/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

 package GUI;

 import Main.Taillard;
 import java.io.File;
 import javax.swing.JFileChooser;
 import javax.swing.JOptionPane;
 
 /**
  *
  * @author Necron
  */
 public class Masukan extends javax.swing.JFrame {
         private File file;
         private JFileChooser fc;
 
         /**
          * Creates new form Input
          */
         public Masukan() {
                 initComponents();
                 fc = new JFileChooser();
         }
 
         /**
          * This method is called from within the constructor to initialize the form.
          * WARNING: Do NOT modify this code. The content of this method is always
          * regenerated by the Form Editor.
          */
         @SuppressWarnings("unchecked")
         // <editor-fold defaultstate="collapsed" desc="Generated
         // Code">//GEN-BEGIN:initComponents
         private void initComponents() {
 
                 jLabel4 = new javax.swing.JLabel();
                 MaksIterasiSpinner = new javax.swing.JSpinner();
                 jLabel5 = new javax.swing.JLabel();
                 jLabel6 = new javax.swing.JLabel();
                 PeluangCOSpinner = new javax.swing.JSpinner();
                 PeluangMutasiSpinner = new javax.swing.JSpinner();
                 jButton2 = new javax.swing.JButton();
                 jButton1 = new javax.swing.JButton();
                 jButton3 = new javax.swing.JButton();
                 jLabel1 = new javax.swing.JLabel();
                 jLabel2 = new javax.swing.JLabel();
                 jLabel3 = new javax.swing.JLabel();
                 BnykIndividuSpinner = new javax.swing.JSpinner();
                 LokasiField = new javax.swing.JTextField();
                 SoalTerpilih = new javax.swing.JComboBox();
                 jLabel7 = new javax.swing.JLabel();
                 jLabel8 = new javax.swing.JLabel();
                 jLabel9 = new javax.swing.JLabel();
                 jLabel10 = new javax.swing.JLabel();
                 jLabel11 = new javax.swing.JLabel();
                 jLabel12 = new javax.swing.JLabel();
                 jLabel13 = new javax.swing.JLabel();
                 jLabel14 = new javax.swing.JLabel();
                 jLabel15 = new javax.swing.JLabel();
 
                 setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
 
                 jLabel4.setText("Peluang crossover*");
 
                 jLabel5.setText("Faktor skala*");
 
                 jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                 jLabel6.setText("Masukkan Data");
 
                 jButton2.setText("Lanjut");
                 jButton2.addActionListener(new java.awt.event.ActionListener() {
                         public void actionPerformed(java.awt.event.ActionEvent evt) {
                                 jButton2ActionPerformed(evt);
                         }
                 });
 
                 jButton1.setText("Cari");
                 jButton1.addActionListener(new java.awt.event.ActionListener() {
                         public void actionPerformed(java.awt.event.ActionEvent evt) {
                                 jButton1ActionPerformed(evt);
                         }
                 });
 
                 jButton3.setText("Kembali");
                 jButton3.addActionListener(new java.awt.event.ActionListener() {
                         public void actionPerformed(java.awt.event.ActionEvent evt) {
                                 jButton3ActionPerformed(evt);
                         }
                 });
 
                 jLabel1.setText("Lokasi file .txt");
 
                 jLabel2.setText("Banyak populasi");
 
                 jLabel3.setText("Maksimum iterasi");
 
                 LokasiField.setEditable(false);
 
                 SoalTerpilih.setModel(new javax.swing.DefaultComboBoxModel(
                                 new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
 
                 jLabel7.setText("Soal ke- ");
 
                 jLabel8.setText(":");
 
                 jLabel9.setText(":");
 
                 jLabel10.setText(":");
 
                 jLabel11.setText(":");
 
                 jLabel12.setText(":");
 
                 jLabel13.setText(":");
 
                 jLabel14.setText("*Ada peluang tidak terjadi apa-apa, jika tidak terjadi apa-apa,");
 
                 jLabel15.setText("maka akan dipilih induk secara acak ke generasi berikutnya.");
 
                 javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                 getContentPane().setLayout(layout);
                 layout.setHorizontalGroup(
                                 layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                 .addGroup(layout.createSequentialGroup()
                                                                 .addContainerGap()
                                                                 .addGroup(layout.createParallelGroup(
                                                                                 javax.swing.GroupLayout.Alignment.LEADING)
                                                                                 .addGroup(layout.createSequentialGroup()
                                                                                                 .addGroup(layout.createParallelGroup(
                                                                                                                 javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                 .addGroup(layout.createSequentialGroup()
                                                                                                                                 .addComponent(jButton3)
                                                                                                                                 .addPreferredGap(
                                                                                                                                                 javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                 .addComponent(jButton2))
                                                                                                                 .addGroup(layout.createSequentialGroup()
                                                                                                                                 .addGroup(layout.createParallelGroup(
                                                                                                                                                 javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                 .addComponent(jLabel1)
                                                                                                                                                 .addComponent(jLabel7)
                                                                                                                                                 .addComponent(jLabel5)
                                                                                                                                                 .addComponent(jLabel4)
                                                                                                                                                 .addComponent(jLabel3)
                                                                                                                                                 .addComponent(jLabel2))
                                                                                                                                 .addPreferredGap(
                                                                                                                                                 javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                                 41,
                                                                                                                                                 Short.MAX_VALUE)
                                                                                                                                 .addGroup(layout.createParallelGroup(
                                                                                                                                                 javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                 .addGroup(layout.createSequentialGroup()
                                                                                                                                                                 .addGroup(layout.createParallelGroup(
                                                                                                                                                                                 javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                                                 .addComponent(jLabel9)
                                                                                                                                                                                 .addComponent(jLabel8)
                                                                                                                                                                                 .addComponent(jLabel10)
                                                                                                                                                                                 .addComponent(jLabel11)
                                                                                                                                                                                 .addComponent(jLabel12)
                                                                                                                                                                                 .addComponent(jLabel13))
                                                                                                                                                                 .addPreferredGap(
                                                                                                                                                                                 javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                                 .addGroup(layout.createParallelGroup(
                                                                                                                                                                                 javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                                                 .addGroup(layout.createSequentialGroup()
                                                                                                                                                                                                 .addComponent(LokasiField,
                                                                                                                                                                                                                 javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                                 204,
                                                                                                                                                                                                                 javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                                 .addPreferredGap(
                                                                                                                                                                                                                 javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                                                                 .addComponent(jButton1))
                                                                                                                                                                                 .addGroup(layout.createParallelGroup(
                                                                                                                                                                                                 javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                                                                                 false)
                                                                                                                                                                                                 .addComponent(SoalTerpilih,
                                                                                                                                                                                                                 javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                                                                                 0,
                                                                                                                                                                                                                 javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                                                 Short.MAX_VALUE)
                                                                                                                                                                                                 .addComponent(PeluangCOSpinner,
                                                                                                                                                                                                                 javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                                                                 .addComponent(MaksIterasiSpinner,
                                                                                                                                                                                                                 javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                                                                 .addComponent(BnykIndividuSpinner,
                                                                                                                                                                                                                 javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                                                                 .addComponent(PeluangMutasiSpinner,
                                                                                                                                                                                                                 javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                                                                                 javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                                                 57,
                                                                                                                                                                                                                 Short.MAX_VALUE))))
                                                                                                                                                 .addComponent(jLabel6))))
                                                                                                 .addContainerGap(25,
                                                                                                                 Short.MAX_VALUE))
                                                                                 .addGroup(layout.createSequentialGroup()
                                                                                                 .addGroup(layout.createParallelGroup(
                                                                                                                 javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                 .addComponent(jLabel14)
                                                                                                                 .addComponent(jLabel15))
                                                                                                 .addContainerGap(
                                                                                                                 javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                 Short.MAX_VALUE)))));
                 layout.setVerticalGroup(
                                 layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                 .addGroup(layout.createSequentialGroup()
                                                                 .addContainerGap()
                                                                 .addComponent(jLabel6,
                                                                                 javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                 41,
                                                                                 javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                 .addGap(18, 18, 18)
                                                                 .addGroup(layout.createParallelGroup(
                                                                                 javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                 .addComponent(jLabel1)
                                                                                 .addComponent(jButton1)
                                                                                 .addComponent(LokasiField,
                                                                                                 javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                 javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                 javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                 .addComponent(jLabel8))
                                                                 .addPreferredGap(
                                                                                 javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                 .addGroup(layout.createParallelGroup(
                                                                                 javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                 .addComponent(jLabel2)
                                                                                 .addComponent(BnykIndividuSpinner,
                                                                                                 javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                 javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                 javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                 .addComponent(jLabel9))
                                                                 .addPreferredGap(
                                                                                 javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                 .addGroup(layout.createParallelGroup(
                                                                                 javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                 .addComponent(MaksIterasiSpinner,
                                                                                                 javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                 javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                 javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                 .addComponent(jLabel10)
                                                                                 .addComponent(jLabel3))
                                                                 .addPreferredGap(
                                                                                 javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                 .addGroup(layout.createParallelGroup(
                                                                                 javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                 .addComponent(PeluangCOSpinner,
                                                                                                 javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                 javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                 javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                 .addComponent(jLabel11)
                                                                                 .addComponent(jLabel4))
                                                                 .addPreferredGap(
                                                                                 javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                 .addGroup(layout.createParallelGroup(
                                                                                 javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                 .addComponent(PeluangMutasiSpinner,
                                                                                                 javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                 javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                 javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                 .addComponent(jLabel12)
                                                                                 .addComponent(jLabel5))
                                                                 .addPreferredGap(
                                                                                 javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                 .addGroup(layout.createParallelGroup(
                                                                                 javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                 .addComponent(SoalTerpilih,
                                                                                                 javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                 javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                 javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                 .addComponent(jLabel7)
                                                                                 .addComponent(jLabel13))
                                                                 .addPreferredGap(
                                                                                 javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                 .addComponent(jLabel14)
                                                                 .addPreferredGap(
                                                                                 javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                 javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                 Short.MAX_VALUE)
                                                                 .addComponent(jLabel15)
                                                                 .addPreferredGap(
                                                                                 javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                 .addGroup(layout.createParallelGroup(
                                                                                 javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                 .addComponent(jButton2)
                                                                                 .addComponent(jButton3))
                                                                 .addContainerGap()));
 
                 pack();
         }// </editor-fold>//GEN-END:initComponents
 
         private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
                 // TODO add your handling code here:
                 try {
                         fc.showSaveDialog(null);
                         file = fc.getSelectedFile();
                         LokasiField.setText(file.getPath() + "");
                 } catch (NullPointerException npe) {
                         JOptionPane.showMessageDialog(null, "Batal mencari");
                 }
         }// GEN-LAST:event_jButton1ActionPerformed
 
         private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
                 // TODO add your handling code here:
                 String lokasiTxt = this.LokasiField.getText();
                 //bnykpopulasi, iterasi, peluangCO, faktor skala, soalTerpilih.
                 int bnykpopulasi = (int) this.BnykIndividuSpinner.getValue();
                 int maksIterasi = (int) this.MaksIterasiSpinner.getValue();
                 int peluangCO = (int) this.PeluangCOSpinner.getValue();
                 double faktor_skala = (int) this.PeluangMutasiSpinner.getValue();
                 int soalTerpilih = Integer.parseInt(this.SoalTerpilih.getSelectedItem().toString()) - 1;
                 Taillard taillard = new Taillard(lokasiTxt, bnykpopulasi, maksIterasi, peluangCO, faktor_skala,soalTerpilih);
                 Hasil h = new Hasil(taillard, soalTerpilih);
                 h.setVisible(true);
                 this.dispose();
         }// GEN-LAST:event_jButton2ActionPerformed
 
         private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
                 HalamanAwal HA = new HalamanAwal();
                 HA.setVisible(true);
                 this.dispose();
         }// GEN-LAST:event_jButton3ActionPerformed
 
         /**
          * @param args the command line arguments
          */
         public static void main(String args[]) {
                 /* Set the Nimbus look and feel */
                 // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                 // (optional) ">
                 /*
                  * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                  * look and feel.
                  * For details see
                  * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                  */
                 try {
                         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                         .getInstalledLookAndFeels()) {
                                 if ("Nimbus".equals(info.getName())) {
                                         javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                         break;
                                 }
                         }
                 } catch (ClassNotFoundException ex) {
                         java.util.logging.Logger.getLogger(Masukan.class.getName()).log(java.util.logging.Level.SEVERE,
                                         null, ex);
                 } catch (InstantiationException ex) {
                         java.util.logging.Logger.getLogger(Masukan.class.getName()).log(java.util.logging.Level.SEVERE,
                                         null, ex);
                 } catch (IllegalAccessException ex) {
                         java.util.logging.Logger.getLogger(Masukan.class.getName()).log(java.util.logging.Level.SEVERE,
                                         null, ex);
                 } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                         java.util.logging.Logger.getLogger(Masukan.class.getName()).log(java.util.logging.Level.SEVERE,
                                         null, ex);
                 }
                 // </editor-fold>
 
                 /* Create and display the form */
                 java.awt.EventQueue.invokeLater(new Runnable() {
                         public void run() {
                                 new Masukan().setVisible(true);
                         }
                 });
         }
 
         // Variables declaration - do not modify//GEN-BEGIN:variables
         private javax.swing.JSpinner BnykIndividuSpinner;
         private javax.swing.JTextField LokasiField;
         private javax.swing.JSpinner MaksIterasiSpinner;
         private javax.swing.JSpinner PeluangCOSpinner;
         private javax.swing.JSpinner PeluangMutasiSpinner;
         private javax.swing.JComboBox SoalTerpilih;
         private javax.swing.JButton jButton1;
         private javax.swing.JButton jButton2;
         private javax.swing.JButton jButton3;
         private javax.swing.JLabel jLabel1;
         private javax.swing.JLabel jLabel10;
         private javax.swing.JLabel jLabel11;
         private javax.swing.JLabel jLabel12;
         private javax.swing.JLabel jLabel13;
         private javax.swing.JLabel jLabel14;
         private javax.swing.JLabel jLabel15;
         private javax.swing.JLabel jLabel2;
         private javax.swing.JLabel jLabel3;
         private javax.swing.JLabel jLabel4;
         private javax.swing.JLabel jLabel5;
         private javax.swing.JLabel jLabel6;
         private javax.swing.JLabel jLabel7;
         private javax.swing.JLabel jLabel8;
         private javax.swing.JLabel jLabel9;
         // End of variables declaration//GEN-END:variables
 }
 